# Change these first
owner: mapmaker-workshop-tools  # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
assignees:
  - two-trick-pony-NL


sites:
  - name: Production
    url: https://mapmaker.nl
  - name: Triage (development)
    url: https://triage.mapmaker.nl
  - name: Status Page
    url: https://status.mapmaker.nl

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mapmaker.nl
  name: Mapmaker Status page
  favicon: https://avatars.githubusercontent.com/u/132359810?s=200&v=4
  logoUrl: https://mapmaker.nl/static/images/mapmaker_logo.png

  introTitle: "**Status page**"
  introMessage: "This is the status page for Mapmaker. Check the associated issues in case of downtime."
  theme: light
  css: "css: "nav { background-color: #fae050 }"
  navbar:
    - title: Status
      href: /
    - title: Incident Issues
      href: https://github.com/mapmaker-workshop-tools/upptime/issues?q=is%3Aissue+is%3Aopen

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
